name: Android CI

on:
  push:
    branches: [ "main" ]  # 触发分支
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        # 自动安装 Android SDK 和构建工具

      - name: Build Release APK
        run: ./gradlew assembleRelease  # 执行 Gradle 构建

      - name: Sign APK (Optional)
        if: success() && github.event_name == 'push'  # 仅对 push 事件签名
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cp ${{ secrets.KEYSTORE }} ./app/mnml.jks  # 从 Secrets 加载 Keystore
          ./gradlew signingReport  # 验证签名配置
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: mnml-screen-recorder
          path: app/build/outputs/apk/release/app-release.apk
